name: Build GPU

on:
  push:
    branches: [ "*" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        env:
          CONDA: /home/runnerx/miniconda3
        with:
          miniconda-version: "latest"

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge gsl
          conda install -c numba/label/dev numba
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Test with pytest
        run: |
          pytest -m gpu -v
